services:
  webpage:
    build: app
    restart: unless-stopped
    command: python app.py
    expose:
      - 8000
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 2G
    env_file:
      - .env
    volumes:
      - ./app:/app
    networks:
      - mongo-net
      - ufiles-stg-net
      - ufiles-net

networks:
  traefik-net:
    external: true
  mongo-net:
    external: true
  ufiles-stg-net:
    external: true
  ufiles-net:
    external: true
