services:
  webpage:
    build: app
    restart: unless-stopped
    command: python app.py
    expose:
      - 8000
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
    env_file:
      - .env
    volumes:
      - ./app:/app
    networks:
      - mongo-net
      - ufiles-stg-net
      - ufiles-net

  worker:
    build: app
    restart: unless-stopped
    command: python runner.py
    env_file:
      - .env
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
          cpus: 1
    volumes:
      - ./app:/app
    networks:
      - mongo-net
    depends_on:
      - webpage

networks:
  traefik-net:
    external: true
  mongo-net:
    external: true
  ufiles-stg-net:
    external: true
  ufiles-net:
    external: true
